"""Gateway contract hooks for the LiteLLM proxy.

The data plane is LiteLLM taken as it comes. This module is the small, explicit
exception: the parts of the public contract (docs/CONTRACT.md) that the proxy
does not implement out of the box.

    * usage is always present, streaming included  (contract §3.4)
    * vendor model names are rejected with a usable error body  (§3.3, §3.5)
    * an alias outside the key's whitelist is 403, not 400  (§3.5)
    * an exhausted budget is 429 with the numbers needed to act  (§3.5)

Every hook is defensive: a bug here must never take the gateway down, so all
non-contract failures are swallowed and the request proceeds as it would have
without the hook.

Loaded through litellm_settings.callbacks in deploy/litellm/config.yaml, which
is generated by `gwctl apply`.
"""

from __future__ import annotations

import datetime
import logging
from typing import Any, Optional

from fastapi import HTTPException
from litellm.integrations.custom_logger import CustomLogger

log = logging.getLogger("gw_hooks")

# Model groups whose name contains this marker are fallback deployments created
# by gwctl. They are internal routing targets, never part of the contract.
FALLBACK_MARKER = "--fallback-"

CHAT_CALL_TYPES = ("completion", "acompletion", "text_completion", "embeddings", "moderation")


class GatewayHooks(CustomLogger):
    """Enforces the public contract in front of the router."""

    async def async_pre_call_hook(
        self,
        user_api_key_dict: Any,
        cache: Any,
        data: dict,
        call_type: str,
    ) -> Optional[dict]:
        self._force_usage(data)

        # Contract violations are raised; anything else is logged and ignored.
        self._check_budget(user_api_key_dict)
        self._check_alias(user_api_key_dict, data)
        return data

    # ------------------------------------------------------------------ usage

    @staticmethod
    def _force_usage(data: dict) -> None:
        """Guarantee a usage block even when the consumer forgot to ask.

        Without this, a streaming consumer gets no token counts and the gateway
        cannot tell it what a request cost.
        """
        try:
            if not data.get("stream"):
                return
            options = data.get("stream_options")
            if not isinstance(options, dict):
                options = {}
            options["include_usage"] = True
            data["stream_options"] = options
        except Exception:  # pragma: no cover - defensive
            log.exception("gw_hooks: could not force stream_options.include_usage")

    # ----------------------------------------------------------------- aliases

    def _check_alias(self, user_api_key_dict: Any, data: dict) -> None:
        requested = data.get("model")
        if not requested:
            return

        allowed = self._allowed_aliases(user_api_key_dict)
        known = self._known_aliases()

        # An empty key whitelist means "not restricted here"; the first barrier
        # (only aliases exist in the model list) still applies.
        if known and requested not in known:
            raise HTTPException(
                status_code=400,
                detail={
                    "error": {
                        "code": "unknown_model_alias",
                        "message": (
                            f"Model '{requested}' is not a valid alias. "
                            "Use one of the available aliases."
                        ),
                        "type": "invalid_request_error",
                    },
                    "available": sorted(allowed or known),
                },
            )

        if allowed and requested not in allowed:
            raise HTTPException(
                status_code=403,
                detail={
                    "error": {
                        "code": "alias_not_permitted",
                        "message": f"Alias '{requested}' is not permitted for this key.",
                        "type": "invalid_request_error",
                    },
                    "available": sorted(allowed),
                },
            )

    @staticmethod
    def _allowed_aliases(user_api_key_dict: Any) -> set:
        models = getattr(user_api_key_dict, "models", None) or []
        return {model for model in models if isinstance(model, str) and FALLBACK_MARKER not in model}

    @staticmethod
    def _known_aliases() -> set:
        """Alias names the router currently serves, fallback groups excluded."""
        try:
            from litellm.proxy.proxy_server import llm_router

            if llm_router is None:
                return set()
            names = llm_router.get_model_names() or []
            return {name for name in names if FALLBACK_MARKER not in name}
        except Exception:  # pragma: no cover - defensive
            log.exception("gw_hooks: could not read the router model list")
            return set()

    # ----------------------------------------------------------------- budgets

    def _check_budget(self, user_api_key_dict: Any) -> None:
        """Answer 429 with enough numbers to decide what to do next.

        LiteLLM enforces the budget itself, but its error body does not say how
        much was spent or when the window resets, which is exactly what the
        caller needs to avoid hammering the gateway.
        """
        try:
            limit = getattr(user_api_key_dict, "max_budget", None)
            spent = getattr(user_api_key_dict, "spend", None)
            if limit is None or spent is None or spent < limit:
                return

            resets_at = getattr(user_api_key_dict, "budget_reset_at", None)
            consumer = getattr(user_api_key_dict, "key_alias", None) or "unknown"
            period = getattr(user_api_key_dict, "budget_duration", None)
        except Exception:  # pragma: no cover - defensive
            log.exception("gw_hooks: could not read budget state")
            return

        raise HTTPException(
            status_code=429,
            detail={
                "error": {
                    "code": "budget_exceeded",
                    "message": f"Budget for consumer '{consumer}' exhausted.",
                    "type": "rate_limit_error",
                },
                "retry_after": _seconds_until(resets_at),
                "budget": {
                    "limit_usd": round(float(limit), 4),
                    "spent_usd": round(float(spent), 4),
                    "period": _period_label(period),
                    "resets_at": _iso(resets_at),
                },
            },
        )


def _seconds_until(moment: Any) -> Optional[int]:
    if not isinstance(moment, datetime.datetime):
        return None
    now = datetime.datetime.now(tz=moment.tzinfo)
    return max(0, int((moment - now).total_seconds()))


def _iso(moment: Any) -> Optional[str]:
    if not isinstance(moment, datetime.datetime):
        return None
    return moment.isoformat().replace("+00:00", "Z")


def _period_label(duration: Any) -> Optional[str]:
    return {"1d": "daily", "7d": "weekly", "30d": "monthly"}.get(duration, duration)


# The instance referenced from litellm_settings.callbacks as
# "gw_hooks.gw_handler".
gw_handler = GatewayHooks()
