package reconcile

import (
	"bytes"
	"fmt"

	"github.com/romandots/llm-gateway/internal/config"
	"gopkg.in/yaml.v3"
)

// GeneratedConfigPath is the LiteLLM configuration file rendered by gwctl,
// relative to the repository root. It is mounted into the proxy container.
const GeneratedConfigPath = "deploy/litellm/config.yaml"

const generatedHeader = `# GENERATED BY gwctl apply — DO NOT EDIT BY HAND.
#
# Source of truth: config/proxy.yaml and the target order in config/models.yaml.
# Model deployments and virtual keys are NOT here: they live in Postgres and are
# reconciled through the LiteLLM Admin API (store_model_in_db).
#
# Changes to this file take effect only after the proxy is restarted:
#   make restart
`

// litellmConfig mirrors the subset of the LiteLLM configuration file that the
// control plane owns.
type litellmConfig struct {
	ModelList       []any             `yaml:"model_list"`
	GeneralSettings map[string]any    `yaml:"general_settings"`
	LiteLLMSettings map[string]any    `yaml:"litellm_settings"`
	RouterSettings  map[string]any    `yaml:"router_settings"`
	Environment     map[string]string `yaml:"environment_variables,omitempty"`
}

// RenderProxyConfig produces the LiteLLM configuration file contents for the
// given gateway configuration. The output is deterministic: rendering twice
// from the same input yields byte-identical files, which is what makes
// `gwctl apply` idempotent.
func RenderProxyConfig(cfg *config.Config) ([]byte, error) {
	fallbacks := make([]map[string][]string, 0, len(cfg.Models.Aliases))
	fallbacks = append(fallbacks, Fallbacks(cfg)...)

	// Bodies must not reach the logs. When body logging is off — the default,
	// and the only sane setting for a shared VPS — LiteLLM is told to drop
	// messages before anything is persisted.
	bodyLogging := cfg.Proxy.Logging.RequestBodies || cfg.Proxy.Logging.ResponseBodies

	doc := litellmConfig{
		ModelList: []any{},
		GeneralSettings: map[string]any{
			"master_key":                       "os.environ/LITELLM_MASTER_KEY",
			"database_url":                     "os.environ/DATABASE_URL",
			"store_model_in_db":                true,
			"store_prompts_in_spend_logs":      bodyLogging,
			"disable_spend_logs":               !cfg.Proxy.Logging.Metadata,
			"allow_requests_on_db_unavailable": false,
		},
		LiteLLMSettings: map[string]any{
			"turn_off_message_logging": !bodyLogging,
			"drop_params":              true,
			"request_timeout":          cfg.Proxy.Request.TimeoutSeconds,
			"num_retries":              cfg.Proxy.Request.NumRetries,
			"callbacks":                []string{"gw_hooks.gw_handler"},
			"cache":                    cfg.Proxy.Cache.Enabled,
		},
		RouterSettings: map[string]any{
			"routing_strategy":       "simple-shuffle",
			"num_retries":            cfg.Proxy.Request.NumRetries,
			"timeout":                cfg.Proxy.Request.TimeoutSeconds,
			"retry_after":            cfg.Proxy.Request.RetryAfterSeconds,
			"allowed_fails":          3,
			"cooldown_time":          30,
			"redis_host":             "os.environ/REDIS_HOST",
			"redis_port":             "os.environ/REDIS_PORT",
			"enable_pre_call_checks": true,
			"fallbacks":              fallbacks,
		},
	}

	if cfg.Proxy.Cache.Enabled {
		doc.LiteLLMSettings["cache_params"] = map[string]any{
			"type": "redis",
			"host": "os.environ/REDIS_HOST",
			"port": "os.environ/REDIS_PORT",
		}
	}

	var buf bytes.Buffer
	buf.WriteString(generatedHeader)

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("render proxy config: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("render proxy config: %w", err)
	}
	return buf.Bytes(), nil
}
